### ISSUE TITLE
Client Registration fails because SMT is unable to identify Client IP Address

### ISSUE THREAD

**Issue by Noatun** [SUSE/smt#63]
System:VM-Guest System
OS: SLES12 SP1
Plattform: x86_64
SMT Version: smt-3.0.11-9.1.x86_64

Description: when a Client tries to Register to SMT Service it gets an Error
[Fri Apr 08 10:06:33.785785 2016] [perl:error] [pid 16026] [client AAA.BBB.CCC.DDD:36884] Can't locate object method "remote_ip" via package "Apache2::Connection" at /srv/www/perl-lib/SMT/Registration.pm line 714.\n

After Searching into this I found the following page: http://blog.branix.net/snippets/can-t-locate-object-method-remote_ip-via-package-apache2-connection

onn_rec->remote_ip and conn_rec->remote_addr
These fields have been renamed in order to distinguish between the client IP address of the connection and the useragent IP address of the request (potentially overridden by a load balancer or proxy). References to either of these fields must be updated with one of the following options, as appropriate for the module:
When you require the IP address of the user agent, which might be connected directly to the server, or might optionally be separated from the server by a transparent load balancer or proxy, use request_rec->useragent_ip and request_rec->useragent_addr.
When you require the IP address of the client that is connected directly to the server, which might be the useragent or might be the load balancer or proxy itself, use conn_rec->client_ip and conn_rec->client_addr.
- http://httpd.apache.org/docs/current/developer/new_api_2_4.html

Looking into /srv/www/perl-lib/SMT/Registration.pm(Line 709-716):
    if($hostname eq "")
    {
        $hostname = $r->connection()->remote_host();
        if(! defined $hostname || $hostname eq "")
        {
            $hostname = $r->connection()->remote_ip();
        }
    }

This Statement is no longer working with apache2-2.4.16-5.1.x86_64 in SLES12 SP1.
Changing the above code to:
    if($hostname eq "")
    {
        $hostname = $r->connection()->remote_host();
        if(! defined $hostname || $hostname eq "")
        {
            $hostname = $r->connection()->client_ip();
        }
    }

did the Trick.

**Comment by mcalmer** [comment]
Fix commited as b4db281a9e060c9544c6f5c0c7905628000b017e

Thanks.
